sudo: required
services: 
    - docker


before_install:
    - docker build -t saadazam86/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true saadazam86/docker-react npm run test